---
- name: "Install | Vscode"
  tags:
    - vscode
  block:
    - name: "Install | Vscode | Dependencies"
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - sudo
          - gnupg
        state: present

    - name: "Install | Vscode | Add Microsoft GPG keys"
      ansible.builtin.apt_key:
        keyring: "/etc/apt/trusted.gpg.d/microsoft.gpg"
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: "Install | Vscode | Add Microsoft APT repo"
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
        state: present
        update_cache: true

    - name: "Install | Vscode | apt-get install vscode"
      ansible.builtin.apt:
        name: code
        state: present

  rescue:
    - name: "Install | Vscode | Error"
      ansible.builtin.debug:
        msg: "Fail vscode install and config"
      changed_when: true
      notify:
        - send failed message
