---
# handlers file for irb_defaults
- name: "Restart sshd server"
  ansible.builtin.service:
    name: sshd
    state: restarted
  listen: restart sshd

- name: "APT update"
  ansible.builtin.apt:
    update_cache: true
  listen: update apt cache
