---
# tasks file for nginx
- name: "Nginx"
  tags:
    - nginx
  block:

    - name: "Stop and disable ervice"
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: false

    - name: "Remove package"
      community.general.pkgng:
        name: "nginx"
        state: absent

    - name: "Remove dirs"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ nginx_etc_dir }}"
        - /var/log/nginx

    - name: "Reminder"
      ansible.builtin.debug:
        msg: "Remove hosts from nginx group"

  rescue:
    - name: "Fail"
      ansible.builtin.debug:
        msg: "Fail"
      changed_when: true
      notify:
        - send failed message
