---
# tasks file for nginx
- name: "Debian"
  tags:
    - nginx
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.deploy.yml" # .{{ ansible_distribution_major_version }}
  when:
    - ansible_distribution == "Debian"
    - "'destroy' not in ansible_run_tags"

- name: "FreeBSD"
  tags:
    - nginx
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.deploy.yml"
  when:
    - ansible_distribution == "FreeBSD"
    - "'destroy' not in ansible_run_tags"

- name: "Debian"
  tags:
    - nginx
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.destroy.yml" # .{{ ansible_distribution_major_version }}
  when:
    - ansible_distribution == "Debian"
    - "'destroy' in ansible_run_tags"

- name: "FreeBSD"
  tags:
    - nginx
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.destroy.yml"
  when:
    - ansible_distribution == "FreeBSD"
    - "'destroy' in ansible_run_tags"
