---
# tasks file for nginx
- name: "Nginx"
  tags:
    - nginx
  block:
    - name: "Dependencies"
      ansible.builtin.apt:
        pkg:
          - "nginx-full"
        state: present

    - name: "Write nginx.conf"
      ansible.builtin.template:
        src: "templates/nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"
        mode: "0600"
        owner: "root"
        group: "root"
      register: nginx_conf_reg

    - name: "Config sites"
      ansible.builtin.include_tasks:
        file: sites.yml
      when: sites | length > 0
      loop: "{{ sites }}"
      loop_control:
        loop_var: loop_site
      register: nginx_sites_conf

    - name: "Check config"
      ansible.builtin.command:
        cmd: "nginx -t"
      register: nginx_conf_check
      changed_when: true
      when: >
          nginx_conf_reg.changed or
          nginx_sites_conf.changed
      failed_when:
        - nginx_conf_check.rc != 0
      notify: "reload nginx"

  rescue:
    - name: "Fail"
      ansible.builtin.debug:
        msg: "Fail"
      changed_when: true
      notify:
        - send failed message
