---
- name: Converge
  hosts: all
  vars:
    dhcpd_subnets:
      - subnet: "172.17.1.0"
        netmask: "255.255.255.0"
        gateway: "172.17.1.2"
        broadcast: "172.17.1.255"
        nameserver: "172.17.1.2"
        start: "172.17.1.3"
        stop: "172.17.1.200"
    dhcpd_no_service:
      - subnet: "192.168.170.0"
        netmask: "255.255.255.0"
    dhcpd_listen_interfaces: "eth0"
    dhcpd_fixed_addresses: []
  tasks:
    - name: "Include ruupert.dhcpd"
      ansible.builtin.include_role:
        name: "ruupert.dhcpd"
