---
# tasks file for ruupert_iptables

- name: "TCP: Allow established, related and inbound traffic"
  block:
    - name: "Allow related and established connections"
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: "Allow new incoming SYN packets TCP"
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item.proto }}"
        destination_port: "{{ item.port }}"
        source: "{{ item.src }}"
        ctstate: NEW
        syn: match
        jump: ACCEPT
        comment: "Accept new connections to port {{ item.port }}."
      with_items: "{{ hostvars[inventory_hostname]['host_vars_iptables'] | default(omit) }}"

  rescue:
    - name: "Feil"
      ansible.builtin.debug:
        msg: "Failfail"
      changed_when: true
      notify:
        - send failed message

- name: "Set default INPUT chain policy to DROP"
  block:
    - name: "Allow management IP"
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item.proto }}"
        destination_port: "{{ item.port }}"
        source: "{{ item.src }}"
        ctstate: NEW
        syn: match
        jump: ACCEPT
        comment: Accept management SSH connections.
      register: reg_mgmt
      with_items: "{{ hostvars[inventory_hostname]['mgmt_iptables'] | default(omit) }}"

    - name: "Print reg_mgmt"
      ansible.builtin.debug:
        msg: "{{ reg_mgmt }}"

    - name: "Set the policy for the INPUT chain to DROP"
      ansible.builtin.iptables:
        chain: INPUT
        policy: DROP
  rescue:
    - name: "Feil"
      ansible.builtin.debug:
        msg: "Failfail"
      changed_when: true
      notify:
        - send failed message
