---
# tasks file for ruupert_iptables

- name: "TCP: Allow established, related and inbound traffic"
  block:
    - name: "Allow related and established connections"
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: "Allow new incoming SYN packets TCP"
      ansible.builtin.iptables:
        rule_num: "{{ item.rulenum }}"
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item.port }}"
        source: "{{ item.src }}"
        ctstate: NEW
        syn: match
        jump: ACCEPT
        comment: "Accept new connections to port {{ item.port }}."
      with_items: "{{ hostvars[inventory_hostname]['host_vars_iptables']['allow']['tcp'] | default(omit) }}"

  rescue:
    - name: "Feil"
      ansible.builtin.debug:
        msg: "Failfail"
      changed_when: true
      notify:
        - send failed message

# schange last will have to add above a block that will allow management access
# only if succesful then change policy here
- name: "Set default INPUT chain policy to DROP"
  block:
    - name: "Allow management IP"
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: "{{ item }}"
        ctstate: NEW
        syn: match
        jump: ACCEPT
        comment: Accept management SSH connections.
      with_items: "{{ hostvars[inventory_hostname]['host_vars_mgmt_src_ip'] }}"

    - name: "Set the policy for the INPUT chain to DROP"
      ansible.builtin.iptables:
        chain: INPUT
        policy: DROP
  rescue:
    - name: "Feil"
      ansible.builtin.debug:
        msg: "Failfail"
      changed_when: true
      notify:
        - send failed message
