---
# tasks file for ruupert.apt_dist_upgrade

- name: Update packages and reboot if needed.
  when: ansible_distribution_d == "Ubuntu" and ansible_distribution_version_d == "18.04" 
  block:

  - name: Update APT package manager repositories cache
    become: true
    apt:
      update_cache: yes
    register: apt_result


  - name: Get upgradeable packages
    become: true
    shell: apt list --upgradeable | awk '{print $1"\t"$2"\t"$6}' | tr -d "]"|sed 's/\/[a-zA-Z0-9]*-[a-zA-Z0-9]*//g'
    register: package_list
    notify: save package_list stdout to file

  - name: Update all packages to the latest version
    become: true
    apt:
      upgrade: dist
    register: result
    changed_when: True
    notify: save result stdout to file

  - name: Check if a reboot is required
    stat:
      path: "/var/run/reboot-required"
    register: p

  - name: Reboot
    become: true
    ansible.builtin.reboot:
      reboot_timeout: 600
    when: p.stat.exists
   

  - name: Notify handlers
    meta: flush_handlers

  rescue:
  - name: feil
    debug:
      msg: "apt dist-upgrade failed"
    changed_when: True
    notify: 
      - save package_list stdout to file
      - save result stdout to file
      - send failed message

  - name: Notify handlers
    meta: flush_handlers


- name: send failed message about unreachable hosts
  debug: 
    msg: "{{ ansible_play_hosts_all | difference(ansible_play_hosts) }}"
  when: ansible_play_hosts != ansible_play_hosts_all
  run_once: true
  changed_when: true
  notify:
    - send failed unreachable 
