---
# tasks file for ruupert_iptables

- name: Set the policy for the INPUT chain to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: "Allow related and established connections"
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: "Allow new incoming SYN packets TCP"
  ansible.builtin.iptables:
    rule_num: "{{ item.rulenum }}"
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item.port }}"
    source: "{{ item.src }}"
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.
  with_items: "{{ hostvars[inventory_hostname]['host_vars_iptables']['allow']['tcp'] }}"
