- name: "Install | mpv"
  tags:
    - mpv
  block:
    - name: "Install | mpv | apt-get"
      ansible.builtin.apt:
        pkg:
          - "mpv"
          - "libva-drm2"
          - "libva-x11-2"
        state: present

    - name: "Install | mpv | Ensure user config dir is present"
      ansible.builtin.file:
        path: "{{ home }}/.config/mpv"
        state: directory
        recurse: true
        mode: "0700"
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: "Install | mpv | Configure mpv"
      ansible.builtin.copy:
        src: "files/mpv.conf"
        dest: "{{ home }}/.config/mpv/mpv.conf"
        mode: "0700"
        owner: "{{ username }}"
        group: "{{ username }}"
  rescue:
    - name: "Install | mpv | Fail"
      ansible.builtin.debug:
        msg: "Fail"
      changed_when: true
      notify:
        - send failed message
