galaxy_info:
  author: Raul Becker
  description: Provides reusable handlers for sending error messages to slack, discord or/and teams.
  license: "MIT"
  min_ansible_version: "2.1"
  platforms:
  - name: Debian
    versions:
    - bookworm
    - bullseye
  galaxy_tags: []
dependencies: []
