---
# tasks file for ca
- name: "Generate CA and ssl certs"
  tags:
    - ca
  ansible.builtin.include_tasks:
    file: "ca.yml"
  args:
    apply:
      delegate_to: localhost
  run_once: true

- name: "Copy certs to remotes"
  tags:
    - ca
  ansible.builtin.include_tasks:
    file: "copy.yml"
