---
- name: "Debian | Preflight"
  tags:
    - always
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.preflight.yml"
  when:
    - ansible_distribution == "Debian"
    - "'update' not in ansible_run_tags"

- name: "Debian | Install"
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.install.yml"
  when:
    - ansible_distribution == "Debian" and "'update' not in ansible_run_tags" and airflow_install

- name: "Debian | Configure"
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.configure.yml"
  when:
    - ansible_distribution == "Debian"
    - "'update' not in ansible_run_tags"

- name: "Debian | Upgrade"
  tags:
    - "update"
    - "never"
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.update.yml"
    apply:
      tags:
        - update
  when:
    - ansible_distribution == "Debian" and "'update' in ansible_run_tags" and airflow_version > airflow_installed_version.stdout
