---
# tasks file for irb_defaults

- name: "Configure APT sources.list"
  tags:
    - cis
  block:
    - name: "Configure APT sources.list | Write templated file"
      ansible.builtin.template:
        src: "files//apt.sources.list.j2"
        dest: "/etc/apt/sources.list"
        mode: "0644"
        owner: "root"
        group: "root"
      when: "'debian' in group_names"
      notify: update apt cache

  rescue:
    - name: "Fail"
      ansible.builtin.debug:
        msg: "Something went wrong"
      changed_when: true
      notify:
        - send failed message

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers


- name: "Install packages"
  tags:
    - defaults
  when: "'linux' in group_names"
  block:
    - name: "Install"
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"

  rescue:
    - name: "Feil"
      ansible.builtin.debug:
        msg: "FeilFail"
      changed_when: true
      notify:
        - send failed message

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

- name: "Time"
  tags:
    - defaults
  when: "'linux' in group_names"
  block:
    - name: "Set timezone"
      community.general.timezone:
        name: "{{ timezone }}"

  rescue:
    - name: "Feil"
      ansible.builtin.debug:
        msg: "FeilFail"
      changed_when: true
      notify:
        - send failed message

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers


- name: "Configure sshd"
  tags:
    - defaults
  when: "'linux' in group_names"
  block:
    - name: "Write templated sshd_config_tmp"
      ansible.builtin.template:
        src: "templates/sshd_config.j2"
        dest: "/etc/ssh/sshd_config_tmp"
        mode: "0644"
        owner: "root"
        group: "root"
      register: irb_defaults_sshd_config_reg

    - name: "Check verify sshd_config_tmp" # noqa: no-handler
      ansible.builtin.command:
        cmd: "sshd -t -f /etc/ssh/sshd_config_tmp"
      when: irb_defaults_sshd_config_reg.changed
      failed_when: irb_defaults_sshd_config_tmp_reg.rc != 0
      changed_when: irb_defaults_sshd_config_reg.changed
      register: irb_defaults_sshd_config_tmp_reg

    - name: "Copy tmp file over current sshd_config" # noqa: no-handler
      ansible.builtin.copy:
        src: "/etc/ssh/sshd_config_tmp"
        dest: "/etc/ssh/sshd_config"
        remote_src: true
        mode: "0644"
        owner: "root"
        group: "root"
      when:
        - irb_defaults_sshd_config_reg.changed
        - irb_defaults_sshd_config_tmp_reg.rc != 0
      notify:
        - restart sshd
  rescue:
    - name: "Feil"
      ansible.builtin.debug:
        msg: "FeilFail"
      changed_when: true
      notify:
        - send failed message

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
