---
# 3 Network Configuration - page 284

- name: "3.1 Disable unused network protocols and devices - page 285"
  tags:
    - cis
  block:
#    - name: "3.1.1 Ensure system is checked to determine if IPv6 is enabled (Manual) - page 286"
#      ansible.builtin.debug:
#        msg: "------------Unimplemented--------------"
#      changed_when: true
#    - name: "3.1.2 Ensure wireless interfaces are disabled (Automated) - page 290"
#      ansible.builtin.debug:
#        msg: "------------Unimplemented--------------"
#      changed_when: true
    - name: "3.1.3 Ensure DCCP is disabled (Automated) - page 293"
      community.general.modprobe:
        name: dccp
        state: absent
    - name: "3.1.4 Ensure SCTP is disabled (Automated) - page 297"
      community.general.modprobe:
        name: sctp
        state: absent
    - name: "3.1.5 Ensure RDS is disabled (Automated) - page 301"
      community.general.modprobe:
        name: rds
        state: absent
    - name: "3.1.6 Ensure TIPC is disabled (Automated) - page 305"
      community.general.modprobe:
        name: tipc
        state: absent
  rescue:
    - name: "Fail"
      ansible.builtin.debug:
        msg: "Something went wrong"
      changed_when: true
      notify:
        - send failed message

- name: "Flush handlers"
  tags:
    - cis
  ansible.builtin.meta: flush_handlers

- name: "3.2 Network Parameters (Host Only) - page 309"
  tags:
    - cis
  block:
    - name: "3.2.1 Ensure packet redirect sending is disabled (Automated) - page 310 - net.ipv4.conf.all.send_redirects=0"
      ansible.posix.sysctl:
        name: "net.ipv4.conf.all.send_redirects"
        value: "0"
    - name: "3.2.1 Ensure packet redirect sending is disabled (Automated) - page 310 - net.ipv4.conf.default.send_redirects=0"
      ansible.posix.sysctl:
        name: "net.ipv4.conf.default.send_redirects"
        value: "0"
    - name: "3.2.2 Ensure IP forwarding is disabled (Automated) - page 314 - net.ipv4.ip_forward=0"
      ansible.posix.sysctl:
        name: "net.ipv4.ip_forward"
        value: "0"
      when: "not 'router' in group_names"

    - name: "3.2.2 Ensure IP forwarding is disabled (Automated) - page 314 - net.ipv6.conf.all.forwarding=0"
      ansible.posix.sysctl:
        name: "net.ipv6.conf.all.forwarding"
        value: "0"
  rescue:
    - name: "Fail"
      ansible.builtin.debug:
        msg: "Something went wrong"
      changed_when: true
      notify:
        - send failed message

- name: "Flush handlers"
  tags:
    - cis
  ansible.builtin.meta: flush_handlers

- name: "3.3 Network Parameters (Host and Router) - page 320"
  tags:
    - cis
  block:
    - name: "3.3.1 Ensure source routed packets are not accepted (Automated) - page 321 - IPV4 - net.ipv4.conf.all.accept_source_route=0"
      ansible.posix.sysctl:
        name: "net.ipv4.conf.all.accept_source_route"
        value: "0"
    - name: "3.3.1 Ensure source routed packets are not accepted (Automated) - page 321 - IPV4 net.ipv4.conf.default.accept_source_route=0"
      ansible.posix.sysctl:
        name: "net.ipv4.conf.default.accept_source_route"
        value: "0"
    - name: "3.3.1 Ensure source routed packets are not accepted (Automated) - page 321 - IPV6 - net.ipv6.conf.all.accept_source_route=0"
      ansible.posix.sysctl:
        name: "net.ipv6.conf.all.accept_source_route"
        value: "0"
    - name: "3.3.1 Ensure source routed packets are not accepted (Automated) - page 321 - IPV6 - net.ipv6.conf.default.accept_source_route=0"
      ansible.posix.sysctl:
        name: "net.ipv6.conf.default.accept_source_route"
        value: "0"
    - name: "3.3.2 Ensure ICMP redirects are not accepted (Automated) - page 327 - IPV4 - net.ipv4.conf.all.accept_redirects=0"
      ansible.posix.sysctl:
        name: "net.ipv4.conf.all.accept_redirects"
        value: "0"
    - name: "3.3.2 Ensure ICMP redirects are not accepted (Automated) - page 327 - IPV4 - net.ipv4.conf.default.accept_redirects=0"
      ansible.posix.sysctl:
        name: "net.ipv4.conf.default.accept_redirects"
        value: "0"
    - name: "3.3.2 Ensure ICMP redirects are not accepted (Automated) - page 327 - IPV6 - net.ipv6.conf.all.accept_redirects=0"
      ansible.posix.sysctl:
        name: "net.ipv6.conf.all.accept_redirects"
        value: "0"
    - name: "3.3.2 Ensure ICMP redirects are not accepted (Automated) - page 327 - IPV6 - net.ipv6.conf.default.accept_redirects=0"
      ansible.posix.sysctl:
        name: "net.ipv6.conf.default.accept_redirects"
        value: "0"
    - name: "3.3.3 Ensure secure ICMP redirects are not accepted (Automated) - page 333  net.ipv4.conf.default.secure_redirects=0"
      ansible.posix.sysctl:
        name: "net.ipv4.conf.default.secure_redirects"
        value: "0"
    - name: "3.3.3 Ensure secure ICMP redirects are not accepted (Automated) - page 333 - net.ipv4.conf.all.secure_redirects=0"
      ansible.posix.sysctl:
        name: "net.ipv4.conf.all.secure_redirects"
        value: "0"
#    - name: "3.3.4 Ensure suspicious packets are logged (Automated) - page 337 - net.ipv4.conf.all.log_martians=1"
#      ansible.posix.sysctl:
#        name: "net.ipv4.conf.all.log_martians"
#        value: "1"
#    - name: "3.3.4 Ensure suspicious packets are logged (Automated) - page 337 - net.ipv4.conf.default.log_martians=1"
#      ansible.posix.sysctl:
#        name: "net.ipv4.conf.default.log_martians"
#        value: "1"
    - name: "3.3.5 Ensure broadcast ICMP requests are ignored (Automated) - page 341 - net.ipv4.icmp_echo_ignore_broadcasts=1"
      ansible.posix.sysctl:
        name: "net.ipv4.icmp_echo_ignore_broadcasts"
        value: "1"
    - name: "3.3.6 Ensure bogus ICMP responses are ignored (Automated) - page 345 - net.ipv4.icmp_ignore_bogus_error_responses=1"
      ansible.posix.sysctl:
        name: "net.ipv4.icmp_ignore_bogus_error_responses"
        value: "1"
    - name: "3.3.7 Ensure Reverse Path Filtering is enabled (Automated) - page 349 - net.ipv4.conf.all.rp_filter=1"
      ansible.posix.sysctl:
        name: "net.ipv4.conf.all.rp_filter"
        value: "1"
    - name: "3.3.7 Ensure Reverse Path Filtering is enabled (Automated) - page 349 - net.ipv4.conf.default.rp_filter=1"
      ansible.posix.sysctl:
        name: "net.ipv4.conf.default.rp_filter"
        value: "1"
    - name: "3.3.8 Ensure TCP SYN Cookies is enabled (Automated) - page 353 - net.ipv4.tcp_syncookies=1"
      ansible.posix.sysctl:
        name: "net.ipv4.tcp_syncookies"
        value: "1"
    - name: "3.3.9 Ensure IPv6 router advertisements are not accepted (Automated) - page 357 - net.ipv6.conf.all.accept_ra=0"
      ansible.posix.sysctl:
        name: "net.ipv6.conf.all.accept_ra"
        value: "0"
    - name: "3.3.9 Ensure IPv6 router advertisements are not accepted (Automated) - page 357 - net.ipv6.conf.default.accept_ra"
      ansible.posix.sysctl:
        name: "net.ipv6.conf.default.accept_ra"
        value: "0"
  rescue:
    - name: "Fail"
      ansible.builtin.debug:
        msg: "Something went wrong"
      changed_when: true
      notify:
        - send failed message

- name: "Flush handlers"
  tags:
    - cis
  ansible.builtin.meta: flush_handlers

# # 3.5 Firewall Configuration - page 363
# - name: "3.5.1 Configure UncomplicatedFirewall - page 364"
#   tags:
#     - cis
#   block:
#     - name: "3.5.1.1 Ensure ufw is installed (Automated) - page 365"
#       ansible:
#     - name: "3.5.1.2 Ensure iptables-persistent is not installed with ufw (Automated) - page 367"
#       ansible:
#     - name: "3.5.1.3 Ensure ufw service is enabled (Automated) - page 369"
#       ansible:
#     - name: "3.5.1.4 Ensure ufw loopback traffic is configured (Automated) - page 372"
#       ansible:
#     - name: "3.5.1.5 Ensure ufw outbound connections are configured (Manual) - page 374"
#       ansible:
#     - name: "3.5.1.6 Ensure ufw firewall rules exist for all open ports (Automated) - page 376"
#       ansible:
#     - name: "3.5.1.7 Ensure ufw default deny firewall policy (Automated) - page 378"
#       ansible:
#   rescue:
#     - name: "Fail"
#       ansible.builtin.debug:
#         msg: "Something went wrong"
#       changed_when: true
#       notify:
#         - send failed message

# - name: "3.5.2 Configure nftables - page 380"
#   tags:
#     - cis
#   block:
#     - name: "3.5.2.1 Ensure nftables is installed (Automated) - page 383"
#       ansible:
#     - name: "3.5.2.2 Ensure ufw is uninstalled or disabled with nftables (Automated) - page 385"
#       ansible:
#     - name: "3.5.2.3 Ensure iptables are flushed with nftables (Manual) - page 387"
#       ansible:
#     - name: "3.5.2.4 Ensure a nftables table exists (Automated) - page 389"
#       ansible:
#     - name: "3.5.2.5 Ensure nftables base chains exist (Automated) - page 391"
#       ansible:
#     - name: "3.5.2.6 Ensure nftables loopback traffic is configured (Automated) - page 393"
#       ansible:
#     - name: "3.5.2.7 Ensure nftables outbound and established connections are configured (Manual) - page 395"
#       ansible:
#     - name: "3.5.2.8 Ensure nftables default deny firewall policy (Automated) - page 397"
#       ansible:
#     - name: "3.5.2.9 Ensure nftables service is enabled (Automated) - page 399"
#       ansible:
#     - name: "3.5.2.10 Ensure nftables rules are permanent (Automated) - page 401"
#       ansible:
#   rescue:
#     - name: "Fail"
#       ansible.builtin.debug:
#         msg: "Something went wrong"
#       changed_when: true
#       notify:
#         - send failed message


# # 3.5.3 Configure iptables - page 405

# - name: "3.5.3.1 Configure iptables software - page 406"
#   tags:
#     - cis
#   block:
#     - name: "3.5.3.1.1 Ensure iptables packages are installed (Automated) - page 407"
#       ansible:
#     - name: "3.5.3.1.2 Ensure nftables is not installed with iptables (Automated) - page 409"
#       ansible:
#     - name: "3.5.3.1.3 Ensure ufw is uninstalled or disabled with iptables (Automated) - page 411"
#       ansible:
#   rescue:
#     - name: "Fail"
#       ansible.builtin.debug:
#         msg: "Something went wrong"
#       changed_when: true
#       notify:
#         - send failed message


# - name: "3.5.3.2 Configure IPv4 iptables - page 413"
#   tags:
#     - cis
#   block:
#     - name: "3.5.3.2.1 Ensure iptables default deny firewall policy (Automated) - page 414"
#       ansible:
#     - name: "3.5.3.2.2 Ensure iptables loopback traffic is configured (Automated) - page 416"
#       ansible:
#     - name: "3.5.3.2.3 Ensure iptables outbound and established connections are configured (Manual) - page 418"
#       ansible:
#     - name: "3.5.3.2.4 Ensure iptables firewall rules exist for all open ports (Automated) - page 420"
#       ansible:
#   rescue:
#     - name: "Fail"
#       ansible.builtin.debug:
#         msg: "Something went wrong"
#       changed_when: true
#       notify:
#         - send failed message


# - name: "3.5.3.3 Configure IPv6 ip6tables - page 423"
#   tags:
#     - cis
#   block:
#     - name: "3.5.3.3.1 Ensure ip6tables default deny firewall policy (Automated) - page 424"
#       ansible:
#     - name: "3.5.3.3.2 Ensure ip6tables loopback traffic is configured (Automated) - page 427"
#       ansible:
#     - name: "3.5.3.3.3 Ensure ip6tables outbound and established connections are configured (Manual) - page 430"
#       ansible:
#     - name: "3.5.3.3.4 Ensure ip6tables firewall rules exist for all open ports (Automated) - page 433"
#       ansible:
#   rescue:
#     - name: "Fail"
#       ansible.builtin.debug:
#         msg: "Something went wrong"
#       changed_when: true
#       notify:
#         - send failed message
