---
# tasks file for cis
#

####################################
#
# Explicitly enable ipv6. ipv6 stack disabled would have at least nginx webservers default site configuration broken.
# Meaning that if ipv6 is disabled and nginx is installed automatically or manually the systemd nginx service would fail to start and would
# require manual intervention. To use ansible builtin package install tools the last thing you want is to do exceptions for possible packages
# that by default have configuration for ipv6
#
####################################
# - name: 'EXCEPTION: Enable IPv6'
#   tags:
#     - cis
#   when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "18.04"
#   block:
#     - name: 'Ensure that /etc/default/grub does not disable ipv6'
#       ansible.builtin.replace:
#         path: '/etc/default/grub'
#         regexp: '^GRUB_CMDLINE_LINUX="ipv6.disable=1"$'
#         replace: 'GRUB_CMDLINE_LINUX=""'
#       register: grub_config_update
#     - name: 'Update grub' # noqa: no-handler
#       ansible.builtin.command: 'update-grub'
#       register: grub_updated
#       when: grub_config_update.changed
#     - name: 'Reboot and wait' # noqa: no-handler
#       ansible.builtin.reboot:
#         reboot_timeout: 600
#         test_ansible.builtin.command: 'sysctl net.ipv6'
#       when: grub_updated.changed
#   rescue:
#     - name: 'Send failure message'
#       ansible.builtin.debug:
#         msg: 'fail'
#       changed_when: true
#       notify:
#         - send failed message

# - name: "0 debug vars"
#   tags:
#     - cis
#   ansible.builtin.debug:
#     msg: "{{ cis_debian11 }}"

- name: "1. Initial setup"
  tags:
    - cis
  ansible.builtin.include_tasks:
    file: "tasks/{{ ansible_distribution_release }}_ch1.yml"

- name: "2. Setup"
  tags:
    - cis
  ansible.builtin.include_tasks:
    file: "tasks/{{ ansible_distribution_release }}_ch2.yml"

- name: "3. Setup"
  tags:
    - cis
  ansible.builtin.include_tasks:
    file: "tasks/{{ ansible_distribution_release }}_ch3.yml"

- name: "4. Setup"
  tags:
    - cis
  ansible.builtin.include_tasks:
    file: "tasks/{{ ansible_distribution_release }}_ch4.yml"

- name: "5. Setup"
  tags:
    - cis
  ansible.builtin.include_tasks:
    file: "tasks/{{ ansible_distribution_release }}_ch5.yml"

- name: "6. Setup"
  tags:
    - cis
  ansible.builtin.include_tasks:
    file: "tasks/{{ ansible_distribution_release }}_ch6.yml"
