---
- name: "{{ ansible_distribution }} | {{ role_name }}"
  when:
    - ansible_distribution in dhcpd_distributions
  block:

    - name: "preflight"
      vars:
        role_action: "preflight"
      ansible.builtin.include_tasks:
        file: "preflight.yml"
      when:
        - dhcpd_act != 'destroy'

    - name: "{{ ansible_distribution }} | preflight"
      vars:
        role_action: "preflight"
      tags:
        - always
      ansible.builtin.include_tasks:
        file: "{{ ansible_distribution }}/preflight.yml"
      when:
        - dhcpd_act != 'destroy'

    - name: "{{ ansible_distribution }} | redeploy"
      vars:
        role_action: "{{ main_item }}"
      ansible.builtin.include_tasks:
        file: "{{ ansible_distribution }}/{{ main_item }}.yml"
      with_items:
        - "destroy"
        - "deploy"
        - "configure"
      loop_control:
        loop_var: main_item
      when:
        - dhcpd_act == 'redeploy'

    - name: "{{ ansible_distribution }} | deploy"
      vars:
        role_action: "{{ main_item }}"
      ansible.builtin.include_tasks:
        file: "{{ ansible_distribution }}/{{ main_item }}.yml"
      with_items:
        - "deploy"
        - "configure"
      loop_control:
        loop_var: main_item
      when:
        - dhcpd_act == 'deploy'

    - name: "{{ ansible_distribution }} | configure"
      vars:
        role_action: "configure"
      ansible.builtin.include_tasks:
        file: "{{ ansible_distribution }}/configure.yml"
      when:
        - dhcpd_act == 'reconfigure'

    - name: "{{ ansible_distribution }} | upgrade"
      vars:
        role_action: "upgrade"
      ansible.builtin.include_tasks:
        file: "{{ ansible_distribution }}/{{ main_item }}.yml"
      with_items:
        - deploy
        - configure
      loop_control:
        loop_var: main_item
      when:
        - dhcpd_act == 'upgrade'

    - name: "{{ ansible_distribution }} | destroy"
      vars:
        role_action: "destroy"
      ansible.builtin.include_tasks:
        file: "{{ ansible_distribution }}/destroy.yml"
      when:
        - dhcpd_act == 'destroy'

    - name: "Flush handlers"
      ansible.builtin.meta: flush_handlers
      when:
        - dhcpd_flush_handlers

  rescue:
    - name: "{{ ansible_distribution }} | {{ role_name }} | failed"
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }} | {{ role_name }} | failed"
      notify:
        - send failed message
