---
# tasks file for dhcpd
- name: "ISC dhcpd"
  tags:
    - dhcpd
  block:

    - name: "ISC dhcpd | Install dependencies"
      ansible.builtin.apt:
        pkg:
          - isc-dhcp-server
        state: present
        # update_cache: true

    - name: "ISC dhcpd | Write /etc/default/isc-dhpc-server"
      ansible.builtin.template:
        src: "templates/etc-default-isc-dhcp-server.j2"
        dest: "/etc/default/isc-dhcp-server"
        mode: "0644"
        owner: "root"
        group: "root"

    - name: "ISC dhcpd | Write /etc/dhcp/dhcpd.conf"
      ansible.builtin.template:
        src: "templates/etc-dhcp-dhcpd.conf.j2"
        dest: "/etc/dhcp/dhcpd.conf"
        mode: "0600"
        owner: "root"
        group: "root"
      notify:
        - check config
        - restart dhcpd

    - name: "ISC dhcpd | Service started"
      ansible.builtin.service:
        name: "isc-dhcp-server"
        state: started

  rescue:
    - name: "ISC dhcpd | Error"
      ansible.builtin.debug:
        msg: "Error"
      changed_when: true
      notify:
        - send failed message
