- name: "Xorg"
  tags:
    - desktop
  block:
    - name: "Xorg | Install dependencies"
      ansible.builtin.apt:
        pkg:
          - xorg
          - fonts-hack
          - fonts-hack-ttf
          - unzip
          - vainfo
          - mesa-utils
        state: present
  rescue:
    - name: "Fail"
      ansible.builtin.debug:
        msg: "Fail"
      changed_when: true
      notify:
        - send failed message
