- name: "Firmware"
  ansible.builtin.apt:
    pkg:
      - firmware-iwlwifi
      - firmware-intel-sound
      - firmware-sof-signed
      - firmware-amd-graphics
      - libgl1-mesa-dri
      - libglx-mesa0
      - mesa-vulkan-drivers
      - xserver-xorg-video-all
    state: present
