---
# tasks file for arduino
- name: "Debian"
  tags:
    - arduino
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.yml" # .{{ ansible_distribution_major_version }}
  when:
    - ansible_distribution == "Debian"

- name: "FreeBSD"
  tags:
    - arduino
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.yml"
  when:
    - ansible_distribution == "FreeBSD"

- name: "Configure"
  tags:
    - arduino
    - configure
  ansible.builtin.include_tasks:
    file: "configure.yml"
