---
- name: "Install | firefox"
  tags:
    - firefox
  block:
    - name: "Install | firefox | Dependencies"
      ansible.builtin.apt:
        pkg:
          - firefox
        state: present

  rescue:
    - name: "Install | firefox | Error"
      ansible.builtin.debug:
        msg: "Fail firefox install and config"
      changed_when: true
      notify:
        - send failed message
