---
# tasks file for ruupert_reusable_handlers
- name: "Send failed message about unreachable hosts"
  ansible.builtin.debug:
    msg: "{{ ansible_play_hosts_all | difference(ansible_play_hosts) }}"
  when: ansible_play_hosts != ansible_play_hosts_all
  run_once: true
  changed_when:
    - ansible_play_hosts_all != ansible_play_hosts
  delegate_to: localhost
  notify:
    - send failed unreachable
