---
# handlers file for base
- name: "Restart sshd server"
  ansible.builtin.service:
    name: sshd
    state: restarted
  listen: restart sshd

- name: "APT update"
  ansible.builtin.apt:
    update_cache: true
  listen: update apt cache

- name: "Restart freebsd resolv service"
  ansible.builtin.service:
    name: resolv
    state: restarted
  listen: restart freebsd resolv service
