---
# 4 Logging and Auditing - page 436
# 4.1 Configure System Accounting (auditd) - page 437

# - name: "4.1.1 Ensure auditing is enabled - page 439"
#   block:
#     - name: "4.1.1.1 Ensure auditd is installed (Automated) - page 440"
#       ansible:
#     - name: "4.1.1.2 Ensure auditd service is enabled and active (Automated) - page 442"
#       ansible:
#     - name: "4.1.1.3 Ensure auditing for processes that start prior to auditd is enabled (Automated) - page 444"
#       ansible:
#     - name: "4.1.1.4 Ensure audit_backlog_limit is sufficient (Automated) - page 446"
#       ansible:
#   rescue:
#     - name: "Fail"
#       ansible.builtin.debug:
#         msg: "Something went wrong"
#       changed_when: true
#       notify:
#         - send failed message
# - name: "4.1.2 Configure Data Retention - page 448"
#   block:
#     - name: "4.1.2.1 Ensure audit log storage size is configured (Automated) - page 449"
#       ansible:
#     - name: "4.1.2.2 Ensure audit logs are not automatically deleted (Automated) - page 451"
#       ansible:
#     - name: "4.1.2.3 Ensure system is disabled when audit logs are full (Automated) - page 453"
#       ansible:
#   rescue:
#     - name: "Fail"
#       ansible.builtin.debug:
#         msg: "Something went wrong"
#       changed_when: true
#       notify:
#         - send failed message
# - name: "4.1.3 Configure auditd rules - page 456"
#   block:
#     - name: "4.1.3.1 Ensure changes to system administration scope (sudoers) is collected (Automated) - page 457"
#       ansible:
#     - name: "4.1.3.2 Ensure actions as another user are always logged (Automated) - page 461"
#       ansible:
#     - name: "4.1.3.3 Ensure events that modify the sudo log file are collected (Automated) - page 465"
#       ansible:
#     - name: "4.1.3.4 Ensure events that modify date and time information are collected (Automated) - page 468"
#       ansible:
#     - name: "4.1.3.5 Ensure events that modify the system's network environment are collected (Automated) - page 472"
#       ansible:
#     - name: "4.1.3.6 Ensure use of privileged commands are collected (Automated) - page 476"
#       ansible:
#     - name: "4.1.3.7 Ensure unsuccessful file access attempts are collected (Automated) - page 480"
#       ansible:
#     - name: "4.1.3.8 Ensure events that modify user/group information are collected (Automated) - page 485"
#       ansible:
#     - name: "4.1.3.9 Ensure discretionary access control permission modification events are collected (Automated) - page 489"
#       ansible:
#     - name: "4.1.3.10 Ensure successful file system mounts are collected (Automated) - page 494"
#       ansible:
#     - name: "4.1.3.11 Ensure session initiation information is collected (Automated) - page 498"
#       ansible:
#     - name: "4.1.3.12 Ensure login and logout events are collected (Automated) - page 502"
#       ansible:
#     - name: "4.1.3.13 Ensure file deletion events by users are collected (Automated) - page 506"
#       ansible:
#     - name: "4.1.3.14 Ensure events that modify the system's Mandatory Access Controls are collected (Automated) - page 510"
#       ansible:
#     - name: "4.1.3.15 Ensure successful and unsuccessful attempts to use the chcon command are recorded (Automated) - page 514"
#       ansible:
#     - name: "4.1.3.16 Ensure successful and unsuccessful attempts to use the setfacl command are recorded (Automated) - page 518"
#       ansible:
#     - name: "4.1.3.17 Ensure successful and unsuccessful attempts to use the chacl command are recorded (Automated) - page 522"
#       ansible:
#     - name: "4.1.3.18 Ensure successful and unsuccessful attempts to use the usermod command are recorded (Automated) - page 526"
#       ansible:
#     - name: "4.1.3.19 Ensure kernel module loading unloading and modification is collected (Automated) - page 530"
#       ansible:
#     - name: "4.1.3.20 Ensure the audit configuration is immutable (Automated) - page 535"
#       ansible:
#     - name: "4.1.3.21 Ensure the running and on disk configuration is the same (Manual) - page 538"
#       ansible:
#   rescue:
#     - name: "Fail"
#       ansible.builtin.debug:
#         msg: "Something went wrong"
#       changed_when: true
#       notify:
#         - send failed message
# - name: "4.1.4 Configure auditd file access - page 540"
#   block:
#     - name: "4.1.4.1 Ensure audit log files are mode 0640 or less permissive (Automated) - page 541"
#       ansible:
#     - name: "4.1.4.2 Ensure only authorized users own audit log files (Automated) - page 543"
#       ansible:
#     - name: "4.1.4.3 Ensure only authorized groups are assigned ownership of audit log files (Automated) - page 545"
#       ansible:
#     - name: "4.1.4.4 Ensure the audit log directory is 0750 or more restrictive (Automated) - page 547"
#       ansible:
#     - name: "4.1.4.5 Ensure audit configuration files are 640 or more restrictive (Automated) - page 549"
#       ansible:
#     - name: "4.1.4.6 Ensure audit configuration files are owned by root (Automated) - page 551"
#       ansible:
#     - name: "4.1.4.7 Ensure audit configuration files belong to group root (Automated) - page 553"
#       ansible:
#     - name: "4.1.4.8 Ensure audit tools are 755 or more restrictive (Automated) - page 555"
#       ansible:
#     - name: "4.1.4.9 Ensure audit tools are owned by root (Automated) - page 557"
#       ansible:
#     - name: "4.1.4.10 Ensure audit tools belong to group root (Automated) - page 559"
#       ansible:
#     - name: "4.1.4.11 Ensure cryptographic mechanisms are used to protect the integrity of audit tools (Automated) - page 561"
#       ansible:
#   rescue:
#     - name: "Fail"
#       ansible.builtin.debug:
#         msg: "Something went wrong"
#       changed_when: true
#       notify:
#         - send failed message
# # 4.2 Configure Logging - page 563
# - name: "4.2.1 Configure journald - page 564"
#   block:
#     - name: "4.2.1.1.1 Ensure systemd-journal-remote is installed (Automated) - page 566"
#       ansible:
#     - name: "4.2.1.1.2 Ensure systemd-journal-remote is configured (Manual) - page 568"
#       ansible:
#     - name: "4.2.1.1.3 Ensure systemd-journal-remote is enabled (Manual) - page 570"
#       ansible:
#     - name: "4.2.1.1.4 Ensure journald is not configured to recieve logs from a remote client (Automated) - page 572"
#       ansible:
#   rescue:
#     - name: "Fail"
#       ansible.builtin.debug:
#         msg: "Something went wrong"
#       changed_when: true
#       notify:
#         - send failed message
# - name: "4.2.2 Configure rsyslog - page 586"
#   block:
#     - name: "4.2.1.1 Ensure journald is configured to send logs to a remote log host - page 565"
#       ansible:
#     - name: "4.2.1.2 Ensure journald service is enabled (Automated) - page 574"
#       ansible:
#     - name: "4.2.1.3 Ensure journald is configured to compress large log files (Automated) - page 576"
#       ansible:
#     - name: "4.2.1.4 Ensure journald is configured to write logfiles to persistent disk (Automated) - page 578"
#       ansible:
#     - name: "4.2.1.5 Ensure journald is not configured to send logs to rsyslog (Manual) - page 580"
#       ansible:
#     - name: "4.2.1.6 Ensure journald log rotation is configured per site policy (Manual) - page 582"
#       ansible:
#     - name: "4.2.1.7 Ensure journald default file permissions configured (Manual) - page 584"
#       ansible:
#     - name: "4.2.2.1 Ensure rsyslog is installed (Automated) - page 587"
#       ansible:
#     - name: "4.2.2.2 Ensure rsyslog service is enabled (Automated) - page 589"
#       ansible:
#     - name: "4.2.2.3 Ensure journald is configured to send logs to rsyslog (Manual) - page 591"
#       ansible:
#     - name: "4.2.2.4 Ensure rsyslog default file permissions are configured (Automated) - page 593"
#       ansible:
#     - name: "4.2.2.5 Ensure logging is configured (Manual) - page 595"
#       ansible:
#     - name: "4.2.2.6 Ensure rsyslog is configured to send logs to a remote log host (Manual) - page 598"
#       ansible:
#     - name: "4.2.2.7 Ensure rsyslog is not configured to receive logs from a remote client (Automated) - page 600"
#       ansible:
#     - name: "4.2.3 Ensure all logfiles have appropriate permissions and ownership (Automated) - page 603"
#       ansible:
#   rescue:
#     - name: "Fail"
#       ansible.builtin.debug:
#         msg: "Something went wrong"
#       changed_when: true
#       notify:
#         - send failed message
