---
# tasks file for ruupert_management_users

- name: "Management users"
  tags:
    - mgmt_users
  when: ansible_distribution_release == "bionic" or ansible_distribution_release or "bullseye"
  block:
    - name: "Ensure adm group exists"
      ansible.builtin.group:
        name: "adm"
        state: "present"

    - name: "Create user accounts"
      no_log: true
      ansible.builtin.user:
        name: "{{ item['username'] }}"
        password: "{{ item['password_hash'] }}"
        groups:
          - "adm"
        shell: /bin/bash
      with_items: "{{ users | list }}"

    - name: "Add authorized keys"
      no_log: true
      ansible.posix.authorized_key:
        user: "{{ item['username'] }}"
        key: "{{ item['public_key'] }}"
        state: present
        exclusive: true
      with_items: "{{ users | list }}"

    - name: "Allow adm users to sudo without a password"
      ansible.builtin.lineinfile:
        dest: "/etc/sudoers" # path: in version 2.3
        state: "present"
        regexp: "^%adm"
        line: "%adm ALL=(ALL) NOPASSWD: ALL"
      when: use_sudo

    - name: "Remove old user accounts in remove_users"
      ansible.builtin.user:
        name: "{{ item }}"
        state: "absent"
      with_items: "{{ remove_users }}"

    - name: "Change root password"
      ansible.builtin.user:
        name: root
        password: "{{ root_password_hash }}"
      when: root_password_hash is defined

  rescue:
    - name: "Feil"
      ansible.builtin.debug:
        msg: "Something went wrong"
      changed_when: true
      notify:
        - send failed message

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
