---
# tasks file for ruupert_deploy_electricity_costs

- name: "Deploy electricity_costs"
  when:
    - electricity_costs_helen_username is defined
    - electricity_costs_helen_password is defined
    - electricity_costs_entsoe_apikey is defined
    - electricity_costs_delivery_site is defined
  block:
    - name: "Install dependencies"
      ansible.builtin.apt:
        pkg:
          - "git"
          - "python3"
          - "virtualenv"
          - "python3-virtualenv"
          - "sqlite3"
        state: "present"

    - name: "Create user"
      ansible.builtin.user:
        name: "{{ electricity_costs_user }}"
        home: "{{ electricity_costs_home }}"
        shell: "/usr/sbin/nologin"
        state: present

    - name: "User home dir permissions"
      ansible.builtin.file:
        path: "{{ electricity_costs_home }}"
        state: directory
        recurse: false
        owner: "{{ electricity_costs_user }}"
        group: "{{ electricity_costs_user }}"
        mode: "0700"

    - name: "Git pull"
      ansible.builtin.git:
        repo: "{{ electricity_costs_repo }}"
        dest: "{{ electricity_costs_home }}/app"
        version: "{{ electricity_costs_branch }}"
        force: true
        single_branch: true
      become_user: "{{ electricity_costs_user }}"
      become: true

    - name: "Ensure virtualenv dir is present"
      ansible.builtin.file:
        name: "{{ electricity_costs_home }}/venv"
        mode: "0700"
        owner: "{{ electricity_costs_user }}"
        group: "{{ electricity_costs_user }}"
        state: directory

    - name: "Install python-venv"
      ansible.builtin.pip:
        requirements: "{{ electricity_costs_home }}/app/requirements.txt"
        virtualenv: "{{ electricity_costs_home }}/venv"
        virtualenv_python: "{{ electricity_costs_pyver }}"
      become_user: "{{ electricity_costs_user }}"
      become: true

    - name: "Install github.com/ojarva/python-helen-electricity-usage"
      ansible.builtin.pip:
        name: "git+https://github.com/ojarva/python-helen-electricity-usage"
        virtualenv: "{{ electricity_costs_home }}/venv"
        virtualenv_python: "{{ electricity_costs_pyver }}"
      become: true
      become_user: "{{ electricity_costs_user }}"

    - name: "Create config file"
      ansible.builtin.template:
        src: "templates/dotconfig.yaml.j2"
        dest: "{{ electricity_costs_home }}/app/.config.yaml"
        mode: "0700"
        owner: "{{ electricity_costs_user }}"
        group: "{{ electricity_costs_user }}"

    - name: "Create run.sh"
      ansible.builtin.template:
        src: "templates/run.sh.j2"
        dest: "{{ electricity_costs_home }}/run.sh"
        mode: "0700"
        owner: "{{ electricity_costs_user }}"
        group: "{{ electricity_costs_user }}"

    - name: "Add cronjob"
      ansible.builtin.cron:
        name: Fetch electricity_costs
        weekday: "*"
        minute: "5"
        hour: "15"
        user: "{{ electricity_costs_user }}"
        job: "{{ electricity_costs_home }}/run.sh"
        cron_file: electricity_costs_cron

  rescue:
    - name: "Feil"
      ansible.builtin.debug:
        msg: "FeilFail"
      changed_when: true
      notify:
        - send failed message
