---
# tasks file for idafree
- name: "Debian"
  tags:
    - idafree
    - configure
  ansible.builtin.include_tasks:
    file: "preflight.yml"

- name: "Debian"
  tags:
    - idafree
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.yml" # .{{ ansible_distribution_major_version }}
  when:
    - ansible_distribution == "Debian"

# - name: "FreeBSD"
#   tags:
#     - idafree
#   ansible.builtin.include_tasks:
#     file: "{{ ansible_distribution }}.yml"
#   when:
#     - ansible_distribution == "FreeBSD"

# - name: "Configure"
#   tags:
#     - idafree
#     - configure
#   ansible.builtin.include_tasks:
#     file: "configure.yml"
