---
# tasks file for ntp
- name: "Debian"
  tags:
    - ntp
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.yml" # .{{ ansible_distribution_major_version }}
  when:
    - ansible_distribution == "Debian"

- name: "FreeBSD"
  tags:
    - ntp
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.yml"
  when:
    - ansible_distribution == "FreeBSD"
